export const allDisciplines = [
  {
    name: 'Cardio',
    title: 'disciplines.discipline1.title',
    shortDescription: 'disciplines.discipline1.shortDescription',
    description: 'disciplines.discipline1.description',
    defaultImage: '/images/disciplines/discipline1.png',
    defaultIcon: '/icons/discipline/Cardio.svg',
    link: '/disciplines/Cardio',
  },
  {
    name: 'Dentist',
    title: 'disciplines.discipline2.title',
    shortDescription: 'disciplines.discipline2.shortDescription',
    description: 'disciplines.discipline2.description',
    defaultImage: '/images/disciplines/discipline2.png',
    defaultIcon: '/icons/discipline/Dentist.svg',
    link: '/disciplines/Dentist',
  },
  {
    name: 'Dermato',
    title: 'disciplines.discipline3.title',
    shortDescription: 'disciplines.discipline3.shortDescription',
    description: 'disciplines.discipline3.description',
    defaultImage: '/images/disciplines/discipline3.png',
    defaultIcon: '/icons/discipline/Dermato.svg',
    link: '/disciplines/Dermato',
  },
  {
    name: 'Gastro',
    title: 'disciplines.discipline4.title',
    shortDescription: 'disciplines.discipline4.shortDescription',
    description: 'disciplines.discipline4.description',
    defaultImage: '/images/disciplines/discipline4.png',
    defaultIcon: '/icons/discipline/Gastro.svg',
    link: '/disciplines/Gastro',
  },
  {
    name: 'General',
    title: 'disciplines.discipline5.title',
    shortDescription: 'disciplines.discipline5.shortDescription',
    description: 'disciplines.discipline5.description',
    defaultImage: '/images/disciplines/discipline5.png',
    defaultIcon: '/icons/discipline/General.svg',
    link: '/disciplines/General',
  },
  {
    name: 'Gyneaco',
    title: 'disciplines.discipline6.title',
    shortDescription: 'disciplines.discipline6.shortDescription',
    description: 'disciplines.discipline6.description',
    defaultImage: '/images/disciplines/discipline6.png',
    defaultIcon: '/icons/discipline/Gyneaco.svg',
    link: '/disciplines/Gyneaco',
  },
  {
    name: 'Hearing',
    title: 'disciplines.discipline7.title',
    shortDescription: 'disciplines.discipline7.shortDescription',
    description: 'disciplines.discipline7.description',
    defaultImage: '/images/disciplines/discipline7.png',
    defaultIcon: '/icons/discipline/Hearing.svg',
    link: '/disciplines/Hearing',
  },
  {
    name: 'Kine',
    title: 'disciplines.discipline8.title',
    shortDescription: 'disciplines.discipline8.shortDescription',
    description: 'disciplines.discipline8.description',
    defaultImage: '/images/disciplines/discipline8.png',
    defaultIcon: '/icons/discipline/Kine.svg',
    link: '/disciplines/Kine',
  },
  {
    name: 'Logopede',
    title: 'disciplines.discipline9.title',
    shortDescription: 'disciplines.discipline9.shortDescription',
    description: 'disciplines.discipline9.description',
    defaultImage: '/images/disciplines/discipline9.png',
    defaultIcon: '/icons/discipline/Logopede.svg',
    link: '/disciplines/Logopede',
  },
  {
    name: 'Opthalmo',
    title: 'disciplines.discipline10.title',
    shortDescription: 'disciplines.discipline10.shortDescription',
    description: 'disciplines.discipline10.description',
    defaultImage: '/images/disciplines/discipline10.png',
    defaultIcon: '/icons/discipline/Opthalmo.svg',
    link: '/disciplines/Opthalmo',
  },
  {
    name: 'Pneumo',
    title: 'disciplines.discipline11.title',
    shortDescription: 'disciplines.discipline11.shortDescription',
    description: 'disciplines.discipline11.description',
    defaultImage: '/images/disciplines/discipline11.png',
    defaultIcon: '/icons/discipline/Pneumo.svg',
    link: '/disciplines/Pneumo',
  },
  {
    name: 'Psycho',
    title: 'disciplines.discipline12.title',
    shortDescription: 'disciplines.discipline12.shortDescription',
    description: 'disciplines.discipline12.description',
    defaultImage: '/images/disciplines/discipline12.png',
    defaultIcon: '/icons/discipline/Psycho.svg',
    link: '/disciplines/Psycho',
  },
  {
    name: 'Sang',
    title: 'disciplines.discipline13.title',
    shortDescription: 'disciplines.discipline13.shortDescription',
    description: 'disciplines.discipline13.description',
    defaultImage: '/images/disciplines/discipline13.png',
    defaultIcon: '/icons/discipline/Sang.svg',
    link: '/disciplines/Sang',
  },
]
