export const allDisciplines = [
  {
    id: 'gyneco',
    title: 'disciplines.gyneco.title',
    description: 'disciplines.gyneco.description',
    defaultImage: '/images/disciplines/gyneco.jpg',
    defaultIcon: '/icons/discipline/gyneaco.svg',
    link: '/disciplines/gyneco',
  },
  {
    id: 'kineGlobal',
    title: 'disciplines.kineGlobal.title',
    description: 'disciplines.kineGlobal.description',
    defaultImage: '/images/disciplines/kine.jpg',
    defaultIcon: '/icons/discipline/kine.svg',
    link: '/disciplines/kineGlobal',
  },
  {
    id: 'kinePenale',
    title: 'disciplines.kinePenale.title',
    description: 'disciplines.kinePenale.description',
    defaultImage: '/images/disciplines/kine.jpg',
    defaultIcon: '/icons/discipline/kine.svg',
    link: '/disciplines/kinePenale',
  },
  {
    id: 'orl',
    title: 'disciplines.orl.title',
    description: 'disciplines.orl.description',
    defaultImage: '/images/disciplines/general.jpg',
    defaultIcon: '/icons/discipline/orl.svg',
    link: '/disciplines/orl',
  },
  {
    id: 'audiologie',
    title: 'disciplines.audiologie.title',
    description: 'disciplines.audiologie.description',
    defaultImage: '/images/disciplines/audio.jpg',
    defaultIcon: '/icons/discipline/orl.svg',
    link: '/disciplines/audiologie',
  },
  {
    id: 'psychologie',
    title: 'disciplines.psychologie.title',
    description: 'disciplines.psychologie.description',
    defaultImage: '/images/disciplines/psycho.jpg',
    defaultIcon: '/icons/discipline/psycho.svg',
    link: '/disciplines/psychologie',
  },
  {
    id: 'psychiatrie',
    title: 'disciplines.psychiatrie.title',
    description: 'disciplines.psychiatrie.description',
    defaultImage: '/images/disciplines/psycho.jpg',
    defaultIcon: '/icons/discipline/psycho.svg',
    link: '/disciplines/psychiatrie',
  },
  {
    id: 'sageFemme',
    title: 'disciplines.sageFemme.title',
    description: 'disciplines.sageFemme.description',
    defaultImage: '/images/disciplines/sageFemme.jpg',
    defaultIcon: '/icons/discipline/general.svg',
    link: '/disciplines/sageFemme',
  },
  {
    id: 'podologie',
    title: 'disciplines.podologie.title',
    description: 'disciplines.podologie.description',
    defaultImage: '/images/disciplines/podologie.jpg',
    defaultIcon: '/icons/discipline/general.svg',
    link: '/disciplines/podologie',
  },
  {
    id: 'orthopedie',
    title: 'disciplines.orthopedie.title',
    description: 'disciplines.orthopedie.description',
    defaultImage: '/images/disciplines/general.jpg',
    defaultIcon: '/icons/discipline/general.svg',
    link: '/disciplines/orthopedie',
  },
  {
    id: 'reflexionPlantaire',
    title: 'disciplines.reflexionPlantaire.title',
    description: 'disciplines.reflexionPlantaire.description',
    defaultImage: '/images/disciplines/podologie.jpg',
    defaultIcon: '/icons/discipline/general.svg',
    link: '/disciplines/reflexionPlantaire',
  },
  {
    id: 'dentist',
    title: 'disciplines.dentist.title',
    description: 'disciplines.dentist.description',
    defaultImage: '/images/disciplines/dentist.jpg',
    defaultIcon: '/icons/discipline/dentist.svg',
    link: '/disciplines/dentist',
  },
  {
    id: 'radiologie',
    title: 'disciplines.radiologie.title',
    description: 'disciplines.radiologie.description',
    defaultImage: '/images/disciplines/general.jpg',
    defaultIcon: '/icons/discipline/general.svg',
    link: '/disciplines/radiologie',
  },
  {
    id: 'blood',
    title: 'disciplines.blood.title',
    description: 'disciplines.blood.description',
    defaultImage: '/images/disciplines/blood.jpg',
    defaultIcon: '/icons/discipline/sang.svg',
    link: '/disciplines/blood',
  },
  {
    id: 'neuropsychologie',
    title: 'disciplines.neuropsychologie.title',
    description: 'disciplines.neuropsychologie.description',
    defaultImage: '/images/disciplines/neuro.jpg',
    defaultIcon: '/icons/discipline/general.svg',
    link: '/disciplines/neuropsychologie',
  },
  {
    id: 'sexologie',
    title: 'disciplines.sexologie.title',
    description: 'disciplines.sexologie.description',
    defaultImage: '/images/disciplines/general.jpg',
    defaultIcon: '/icons/discipline/general.svg',
    link: '/disciplines/sexologie',
  },
  {
    id: 'stomatologie',
    title: 'disciplines.stomatologie.title',
    description: 'disciplines.stomatologie.description',
    defaultImage: '/images/disciplines/general.jpg',
    defaultIcon: '/icons/discipline/gastro.svg',
    link: '/disciplines/stomatologie',
  },
  {
    id: 'dietetique',
    title: 'disciplines.dietetique.title',
    description: 'disciplines.dietetique.description',
    defaultImage: '/images/disciplines/diet.jpg',
    defaultIcon: '/icons/discipline/general.svg',
    link: '/disciplines/dietetique',
  },
  {
    id: 'osteopathie',
    title: 'disciplines.osteopathie.title',
    description: 'disciplines.osteopathie.description',
    defaultImage: '/images/disciplines/osteo.jpg',
    defaultIcon: '/icons/discipline/general.svg',
    link: '/disciplines/osteopathie',
  },
]
