export const allSpecialists = [
  {
    title: 'Dr. Laura van der Hoeden',
    firstName: 'Laura',
    lastName: 'van der Hoeden',
    link: '/specialists/lauravanderhodeden',
    disciplines: ['disciplines.discipline1.title', 'disciplines.discipline2.title'],
    mainDiscipline: 'disciplines.discipline1.title',
    avatar: '/images/specialists/lauravanderhodeden.png',
    contact: {
      phone: '06-12345678',
      email: 'example@gmail..com',
      web: 'www.example.com',
    },
    patients: ['patients.patient1'],
    interests: [
      'interests.interest1',
      'interests.interest2',
      'interests.interest3',
      'interests.interest4',
      'interests.interest5',
      'interests.interest6',
    ],
    languages: ['languages.language1', 'languages.language2'],
    description: 'specialists.lauravanderhodeden.description',
  },
  {
    title: 'Dr. jhon doe',
    firstName: 'Jhon',
    lastName: 'Doe',
    link: 'specialists/jhonDoe',
    disciplines: ['disciplines.discipline1.title', 'disciplines.discipline2.title'],
    mainDiscipline: 'disciplines.discipline1.title',
    avatar: '/images/specialists/lauravanderhodeden.png',
    contact: {
      phone: '06-12345678',
      email: 'example@gmail.com',
      web: 'www.example.com',
    },
    interests: ['interests.interest4', 'interests.interest5', 'interests.interest6'],
    languages: ['languages.language1', 'languages.language2'],
    description: 'specialists.lauravanderhodeden.description',
  },
]
